# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00fccb42bbd9135e34696e4e45a2404a9553dca868491b793feabb9957276e820ff432ccfdfecfa771fde658a7e4467dd582ab58f4fb34565810980d73a1b24f

test:
  secret_key_base: b65d4ce8d2b1518acc0722ec8dca7b81e4022ff9369215d058093ba486505d0ee786b1d0c430df4c3fc835014b2312ab85ef6fb5c787900e3355c081572dda53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
